### PR TITLE
Update search routes to use new 2.5 routing

### PR DESCRIPTION
**Pull request by zlayne**
Signed-off-by: Zack Layne <zlayne@redhat.com>

Related Issue: https://github.com/open-cluster-management/backlog/issues/17364

### CODE REVIEW

**Comment by zlayne** [comment]
Hey @dislbenn I pushed another commit for the final search routes. I am seeing the prow/e2e` passing but the `travis` build failing. Any ideas on this? Also do the builds run against a 2.5 RHACM install or are they still using 2.4.z?

**Comment by dislbenn** [comment]
> Hey @dislbenn I pushed another commit for the final search routes. I am seeing the prow/e2e`passing but the`travis` build failing. Any ideas on this? Also, do the builds run against a 2.5 RHACM install or are they still using 2.4.z?

@zlayne The Travis builds are running off RHACM 2.4.z, we would need to update the cluster to use ACM 2.5. It also might be failing because this is off of a forked branch. I see that the build is failing due to the build-harness. https://app.travis-ci.com/github/open-cluster-management/search-e2e-test/jobs/551556071#L355-L357

**Comment by zlayne** [comment]
@dislbenn Thanks makes sense, is there a timetable on the move to use 2.5?

**Comment by zlayne** [comment]
Closing in favor of: https://github.com/open-cluster-management/search-e2e-test/pull/173

**Pull request closed without merging**
